version: 2

registries:
  terraform-private-dnb-core:
    type: terraform-registry
    url: https://app.terraform.io/app/dnb-core/registry/
    token: ${{ secrets.TERRAFORM_REGISTRY_DNB_CORE_TOKEN }}

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/"
    registries:
      - terraform-private-dnb-core
    schedule:
      interval: "weekly"
